### ISSUE TITLE
Add ratings for the 2017 draft

### ISSUE THREAD

**Issue by zo0o0ot** [Leagueify/draftcharts-jetstrap#13]
Lets get this up to date!

**Comment by vinitraj10** [comment]
please explain?

**Comment by zo0o0ot** [comment]
@vinitraj10 I was talking about something like this: http://draftcharts.azurewebsites.net/2017-potential.html

In essence, it's taking pre-draft ratings for NFL draft prospects and showing groupings by school, conference, etc.

I had finished this task without closing it.  Sorry about that.
