### ISSUE TITLE
Add 2017 Senior Bowl watch list as CSV.

### ISSUE THREAD

**Issue by zo0o0ot** [Leagueify/draftcharts-jetstrap#20]
I'm looking to convert the watch list page into data that can be referenced like the other data I have.
http://www.seniorbowl.com/watch-list-profiles.php

Something like CSV would be nice.

Possible order of fields:
School, Player, Position, Height, Weight, Conference

**Comment by AlexanderEllis** [comment]
Hi zo0o0ot, I wrote a python scraper to build a CSV file from that website.  Right now I have it outputting the fields as First Name, Last Name, School, Position, Height, Weight, and Conference.  Would that work?

If you would like, I can add the CSV file and the scraper for future watch-lists (provided they follow the same format).

**Comment by zo0o0ot** [comment]
2017 Potential page now includes a page with the Senior Bowl Watchlist:
Web page: http://draftcharts.azurewebsites.net/2017-potential.html
Chart page: http://public.tableau.com/shared/PSXRS5TY7?:display_count=yes
